= Annotated Torrents

BitTorrent is a popular protocol for peer-to-peer file sharing. However, compared to centralized alternatives, it is far less user-friendly.

Popular media streaming services such as Spotify and Netflix are self-contained applications with graphical user interfaces that allow users to discover and consume content without requiring technical sophistication.

BitTorrent, on the other hand, requires the use of several different programs for the same task. A user must typically use a browser, a BitTorrent client, their operating system's file manager,and a media player.  This is complicated by the wide number of torrent indexes, some private, all with different content, which make it hard to discover torrents to download in the first place.

Fortunately, we believe that applications can be built on top of BitTorrent that provide a user-friendly experience while benefiting from the decentralized and peer-to-peer nature of BitTorrent.

Some such applications have already been built, and some have been quite successful. However, they do not interoperate, and many rely on centralized servers and administration. We believe that we can do better.

By creating a common specification for machine-readable metadata describing the contents of a torrent, different applications can be built that provide rich, user-friendly experiences while sharing a common base of torrents.

By including this standardized metadata in a torrent, torrent creators can make their torrents usable with a wide range of applications that follow the specification.

We call torrents that include such metadata "Annotated Torrents".

The purpose of this repository is to define and document the Annotated Torrent specification, as well as to provide tools and libraries that allow for the creation, verification, and manipulation of Annotated Torrents.

The Annotated Torrent specification and tools are works in progress. We welcome your participation and input.


== Intellectual Property

The Annotated Torrent specification and tools are not intended to facilitate copyright infringement, rather to facilitate the publication and dissemination of non-infringing content.


== Features

Annotated Torrents enable building application on BitTorrent with user-facing features that are not currently practical:

- High quality search and discovery supported by rich, continuously evolving metadata

- Improved data availability by reducing data siloed in torrent indexes

- Automatic processing, presentation, and storage of content without manual intervention
  
- Data authentication and integrity using digital signatures
 
- Timestamp-proven content provenance

- Backwards compatible with existing BitTorrent infrastructure


=== Search and Discovery

Annotated Torrents link the files they contain to rich, continuously evolving metadata in external databases. An audio track might link to its https://musicbrainz.org[MusicBrainz] entry, or a scanned work of art to the corresponding https://www.wikidata.org[Wikidata] item.

Additional information commonly supplied when adding a torrent to an index, category, release information, tags, description, format information, and additional notes are contained within the torrent itself.

This rich, machine readable metadata can be retrieved and indexed, allowing users to search for and discover content via media-rich interfaces using sophisticated search queries.

Since metadata resides in externally linked databases, not within the torrent or on a particular torrent index, the burden of curation and improvement of metadata can be done on a per-work basis, and not on a per-torrent basis, greatly reducing redundant effort.

Additionally, since the contents of torrents is fixed after publishing, links to external metadata databases allow the metadata to evolve and improve, even long after the torrent is first published.


=== Data availability

Currently, when torrent indexes go offline, permanently or temporarily, a great deal of data is lost. Since Annotated Torrent metadata is contained within the torrent, all data will remain available and can easily be re-indexed.

Since metadata is contained within the torrent, adding torrents to a new index simply involves supplying the torrent's info hash, and the index can automatically retrieve metadata from the torrent itself.


=== Processing, Presentation, and Storage

Many user-friendly features, such as converting downloaded data between formats, sorting or organizing data, backing up data, or transferring data to a mobile device, are currently difficult to implement consistently on BitTorrent, given the ad hoc structure of torrents. Files are often compressed, split into multiple parts, or named inconsistently.  Annotated Torrents can thus enable writing apps that perform all these functions and more, without user intervention.


=== Authentication, Integrity, and Provenance

By digitally signing the contents of their torrents, torrent publishers can build a reputation for high-quality releases, without the need for a trusted central entity.

Bitcoin-blockchain rooted timestamps give creators the ability to conclusively demonstrate their authorship of a particular piece of content. We hope that this will enable a distributed tipping system that allow users to directly reward content creators.


=== Backwards Compatibility

Annotated Torrents build on existing technology and are fully backwards compatible with existing BitTorrent trackers, clients, and indexes. Support for Annotated Torrents can be rolled out gradually and incrementally, without needing to overhaul all existing infrastructure in order to begin to reap the benefits.


== Roadmap

- Specification: The Annotated Torrent specification itself

- Library: Software library for validating and interacting with Annotated Torrents

- Creator: Command line application for creating Annotated Torrents

- Index: Server that crawls torrents, retrieves metadata, builds a search index, and exposes that index via a standard API
 
- Client: Graphical application for browsing indexes and downloading content

- Archive: Library management software for maintaining a local or hosted library of content downloaded via the client
